(** Each [Abstract] type can be generated by a ppx_simd directive. *)
module type Abstract = sig
  type t = private int
end

(** [%blend N, N] where each N is in [0,1]. *)
module Blend2 : Abstract

(** [%blend N, N, N, N] where each N is in [0,1]. *)
module Blend4 : Abstract

(** [%blend N, N, N, N, N, N, N, N] where each N is in [0,1]. *)
module Blend8 : Abstract

(** [%shuffle N, N] where each N is in [0,1]. *)
module Shuffle2 : Abstract

(** [%shuffle N, N, N, N] where each N is in [0,3]. *)
module Shuffle4 : Abstract

(** Constants for SSE4.2 string comparison operations. *)
module String : sig
  (** [%bstr S, C, P] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t) *)
  module Bstr : Abstract

  (** [%bstr S, C, P, M] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (M :
      Mask.t) *)
  module Bstrm : Abstract

  (** [%bstr S, C, P, I] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (I :
      Index.t) *)
  module Bstri : Abstract

  (** [%wstr S, C, P] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t) *)
  module Wstr : Abstract

  (** [%wstr S, C, P, M] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (M :
      Mask.t) *)
  module Wstrm : Abstract

  (** [%wstr S, C, P, I] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (I :
      Index.t) *)
  module Wstri : Abstract

  module Signed : sig
    type t =
      | Signed
      | Unsigned
  end

  module Comparison : sig
    type t =
      | Eq_any
      | Eq_each
      | Eq_ordered
      | In_range
  end

  module Polarity : sig
    type t =
      | Pos
      | Neg
      | Masked_pos
      | Masked_neg
  end

  module Index : sig
    type t =
      | Least_sig
      | Most_sig
  end

  module Mask : sig
    type t =
      | Bit_mask
      | Vec_mask
  end
end
