(** Each [Abstract] type can be generated by a ppx_simd directive. *)
module type Abstract = sig
  type t = private int
end

(** [%blend N, N] where each N is in [0,1]. *)
module Blend2 : Abstract

(** [%blend N, N, N, N] where each N is in [0,1]. *)
module Blend4 : Abstract

(** [%blend N, N, N, N, N, N, N, N] where each N is in [0,1]. *)
module Blend8 : Abstract

(** [%shuffle N, N] where each N is in [0,1]. *)
module Shuffle2 : Abstract

(** [%shuffle N, N, N, N] where each N is in [0,3]. *)
module Shuffle4 : Abstract

(** [%shuffle (N, N), (N, N)] where each N is in [0,1]. *)
module Shuffle2x2 : Abstract

(** [%permute N, N] where each N is in [0,1]. *)
module Permute2 : Abstract

(** [%permute N, N, N, N] where each N is in [0,3]. *)
module Permute4 : Abstract

(** [%permute (N, N), (N, N)] where each N is in [0,1]. *)
module Permute2x2 : Abstract

module Float : sig
  (** Constants for float comparisons. *)
  module Comparison : sig
    type t =
      | Equal
      | Less
      | Less_or_equal
      | Unordered
      | Not_equal
      | Not_less
      | Not_less_or_equal
      | Ordered
  end

  (** Constants for float rounding. *)
  module Rounding : sig
    type t =
      | Nearest
      | Negative_infinity
      | Positive_infinity
      | Zero
      | Current
  end
end

(** Constants for SSE4.2 string comparison operations. *)
module String : sig
  (** [%bytes S, C, P] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t) *)
  module Bytes : Abstract

  (** [%bytes S, C, P, M] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (M
      : Mask.t) *)
  module Bytesm : Abstract

  (** [%bytes S, C, P, I] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (I
      : Index.t) *)
  module Bytesi : Abstract

  (** [%words S, C, P] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t) *)
  module Words : Abstract

  (** [%words S, C, P, M] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (M
      : Mask.t) *)
  module Wordsm : Abstract

  (** [%words S, C, P, I] where: (S : Signed.t), (C : Comparison.t), (P : Polarity.t), (I
      : Index.t) *)
  module Wordsi : Abstract

  module Signed : sig
    type t =
      | Signed
      | Unsigned
  end

  module Comparison : sig
    type t =
      | Eq_any
      | Eq_each
      | Eq_ordered
      | In_range
  end

  module Polarity : sig
    type t =
      | Pos
      | Neg
      | Masked_pos
      | Masked_neg
  end

  module Index : sig
    type t =
      | Least_sig
      | Most_sig
  end

  module Mask : sig
    type t =
      | Bit_mask
      | Vec_mask
  end
end
